apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test-git-1
  namespace: default
spec:
  encryptedData:
    credentials.password: AQA5pzZT3s76X+loGEfYvYNoKtyLpwDKdR4M1QsBkewC2uZO6bLKQlDaNVrdLkeX7nhuCClxpZjJ7vBZUSlrjUlSbndCsQefmR9clYEKbXCZq/MvyoKsGCRYhFdJZlLfUc0WG31WF30w9qSpfI7zZoNwnsNiiedYgPdfh11oFJ5kWxFB/I3TQTSupTl3eKWG1Oe9FfuxOBxoh3joVPK0/d/R7HA3vXknzWd646Swccqvq3wRdZYZ8nctvheVN6ly2PRlTW1jCVw7ragUpOlXRySTW3TkMy6l9HDIPrYh/vBnhTvihRsC8bdRz7mEDfWAbOMHTN2f8fPHDWhBjLqONVBJgRngwW8vFG2WSkNvObH0XtxZUsqJQ9cMvl1B+A5+PbOmVDxFVvuLJyFHGRxYPulB3etywm2Ejkluwe876hy9KPtk/7u2oeDZ18lu3fHGPEHfBvc7yHiIRKuBJTWyXt17nSu02DA6+7wBQx5bkw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: test-git-1
      namespace: default

