apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: test1
  project: defaultproject
spec:
  base:
    name: default
    version: 1.23.0
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  sharing:
    enabled: true
    projects:
    - name: '*'
  type: custom
  version: v1
