apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test-git-1
  namespace: default
spec:
  encryptedData:
    credentials.password: AQB9lbBXMm3ku1Bz99SzUFlzeAMO1b/rdHeTeIkyskNyV79skXSh7SLrIDWLQDSpojD67Hugy2WWDr7N8LEsjRSJMgktYbw0wnyLNmasE+R9/ul+NpoR709zugWIB+vqE0CdBayopyjJP+wxeoXjT3SB5ET/l2klauT1KvTkzzQ8pl5sZbZAsIU7gk3xNEnmZHcrnNUpdZcAWk5eeNpVqDLb8E6nN49WlmXURaXPlY7pKyH44hyd9ur2Ms8eEU3gM/WhRhN37k/N5FDLKIAViCJ5NPW+oQueW1SDFhlE02ksvbgniocck4tz/H+YeB+k9DpyBxBMRGIcKESZ02Qy+VwaaxAUgNztgBAm8Wz6gF6I3E8zL/v0EvNQkVQfGcdpxZRMNuEc0wxI81CRXPzL2eKNxGjgjjrtOGeo2E8UMRGLt8k8bfJEI/T8aqyeihLuIENcGaJCB+fRBgSIX1MUz25rrREKnbrAX5DsowhZzA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: test-git-1
      namespace: default

