apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  name: test-git-1
  project: defaultproject
spec:
  agents:
  - name: docker-1
  endpoint: https://github.com/pravin-rafay/test-git-1
  sharing: {}
  type: Git
